name: telegram_app_frontend
description: Internal team social network mobile client built with Flutter.
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  hooks_riverpod: ^2.4.10
  go_router: ^13.2.2
  dio: ^5.4.3+1
  dio_smart_retry: ^6.0.0
  web_socket_channel: ^2.4.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  collection: ^1.18.0
  intl: ^0.19.0
  uuid: ^4.4.0
  logging: ^1.2.0
  flutter_secure_storage: ^9.0.0
  package_info_plus: ^9.0.0
  connectivity_plus: ^6.0.3
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  file_picker: ^8.0.1
  image_picker: ^1.0.7
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  timeago: ^3.6.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2
  state_notifier: ^0.7.2+1
  retry: ^3.1.0
  equatable: ^2.0.5
  encrypt: ^5.0.1
  device_info_plus: ^10.1.0

dependency_overrides:
  analyzer: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.9
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  integration_test:
    sdk: flutter
  # riverpod_generator: ^2.3.9  # Temporarily disabled due to compatibility issues
  # riverpod_annotation: ^2.3.3  # Temporarily disabled due to compatibility issues
  # custom_lint: ^0.6.1  # Temporarily disabled due to compatibility issues
  # riverpod_lint: ^2.4.0  # Temporarily disabled due to compatibility issues

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/
