import 'package:flutter/material.dart';

const ColorScheme lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF0057FF),
  onPrimary: Colors.white,
  secondary: Color(0xFF1F8CFF),
  onSecondary: Colors.white,
  error: Color(0xFFB00020),
  onError: Colors.white,
  background: Color(0xFFF5F7FA),
  onBackground: Color(0xFF1A1C1E),
  surface: Colors.white,
  onSurface: Color(0xFF1A1C1E),
  primaryContainer: Color(0xFFD6E2FF),
  onPrimaryContainer: Color(0xFF001A43),
  secondaryContainer: Color(0xFFCCE5FF),
  onSecondaryContainer: Color(0xFF001F36),
  surfaceVariant: Color(0xFFE0E3EB),
  onSurfaceVariant: Color(0xFF44474E),
  outline: Color(0xFF74777F),
  shadow: Colors.black26,
  inverseSurface: Color(0xFF313033),
  onInverseSurface: Color(0xFFF2F0F4),
  inversePrimary: Color(0xFFAFC6FF),
);

const ColorScheme darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFFAFC6FF),
  onPrimary: Color(0xFF002D6F),
  secondary: Color(0xFF8AC7FF),
  onSecondary: Color(0xFF00344D),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  background: Color(0xFF121316),
  onBackground: Color(0xFFE2E2E5),
  surface: Color(0xFF1D1F23),
  onSurface: Color(0xFFE2E2E5),
  primaryContainer: Color(0xFF0046A0),
  onPrimaryContainer: Color(0xFFDEE2FF),
  secondaryContainer: Color(0xFF004C70),
  onSecondaryContainer: Color(0xFFCCE5FF),
  surfaceVariant: Color(0xFF44474E),
  onSurfaceVariant: Color(0xFFC4C6CF),
  outline: Color(0xFF8E9099),
  shadow: Colors.black87,
  inverseSurface: Color(0xFFE2E2E5),
  onInverseSurface: Color(0xFF1A1C1E),
  inversePrimary: Color(0xFF0057FF),
);
